flask:
  ENV: development
  DEBUG: True
  PROPAGATE_EXCEPTIONS: False
  JSON_AS_ASCII : False
  MAX_CONTENT_LENGTH : 20971520
  UPLOAD_FOLDER : e:\projects\stacks\books
  SQLALCHEMY_DATABASE_URI : mysql+pymysql://root:@localhost:3306/stacks
  SQLALCHEMY_TRACK_MODIFICATIONS : False
  SQLALCHEMY_COMMIT_ON_TEARDOWN : True
  SQLALCHEMY_ECHO : True
  SECRET_KEY : 54683ASDASXCVDSQ8646

log:
  path: ./logs/
  name: flask.log
  # ERROR = 40, WARNING = 30, INFO = 20, DEBG = 10
  level: 10

postgresql:
  host:
  port: 5432
  username: root
  password: zongming
  database: read

whiteList:
  ip: 127.0.0.1
  path: /book,/user,/favicon.ico,/static
